### ISSUE TITLE
Editing scss file seems to do nothing.

### ISSUE THREAD

**Issue by alexxnz** [WASD-Gaming/fgc-scoreboard#1]
Not sure if this is the best place for this, but making changes to the scss file, as mentioned in the readme, doesn't seem to do anything.

I've tried changing the font and font color, and nothing changes in the browser source in OBS. I've gone as far as restarting OBS after saving the changes to the scss file, but I still see the default font configuration.

**Comment by tarikfayad** [comment]
Hey! So to edit scss you actually need a program like [Koala ](http://koala-app.com/) to compile your changes. If you make changes and then have Koala convert the scss to CSS you should be able to make any tweaks.
